server:
  port: 8003

spring:
  security:
    oauth2:
      client:
        registration:
          transaction-client:
            client-id: oauth2-client-server
            client-secret: oauth2-client-server-secret
            authorization-grant-type: client_credentials
            scope: transaction-status:read
        provider:
          transaction-client:
            token-uri: http://localhost:8000/oauth2/token

oauth2:
  resource:
    server-URL: http://localhost:8001